name: My First Github Action
on: [push]
jobs:
  buildApp:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.finished.outputs.text}}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install node_modules
        run: npm install
      - name: Build the Project
        run: npm run build
      - name: Deploy the Project
        run: npm run deploy
      - name: Final Message
        id: finished
        run: echo "::set-output name=text::hello-world-build-job"
  test-app:
    needs: buildApp
    runs-on: ubuntu-latest
    env:
      MY_JOB_OUTPUT: ${{ needs.buildApp.outputs.text }}
    steps:
      - run: echo "YOLO"