name: My First Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install node_modules
        run: npm install
      - name: Build the Project
        run: npm run dev
      - name: Preview Project
        run: npm run preview  